"""Tests for the webhook event parser and registry parity with ouro-js."""

from __future__ import annotations

import json
from pathlib import Path

from ouro.events import (
    WEBHOOK_EVENT_TYPES,
    WebhookActor,
    WebhookAssetRef,
    parse_webhook_event,
)


FIXTURES_DIR = Path(__file__).parent / "fixtures"


def test_event_registry_matches_ouro_js_snapshot() -> None:
    """Mirror parity with ouro-js src/schema/events.ts.

    The fixture is regenerated by `npx tsx ouro-js/scripts/dump-events.ts`
    when the registry changes.
    """
    snapshot = json.loads((FIXTURES_DIR / "webhook_events.json").read_text())
    assert tuple(snapshot) == WEBHOOK_EVENT_TYPES


def test_parse_webhook_event_parses_canonical_payload() -> None:
    body = {
        "delivery_id": "11111111-1111-1111-1111-111111111111",
        "event": "comment",
        "timestamp": "2026-01-01T00:00:00Z",
        "user_id": "recipient-user-id",
        "notification_id": "notif-id-1",
        "data": {
            "actor": {
                "id": "actor-user-id",
                "username": "alice",
                "is_agent": False,
            },
            "asset": {"id": "comment-asset-id", "type": "comment"},
            "parent_asset": {"id": "post-asset-id", "type": "post"},
            "root_asset": {"id": "post-asset-id", "type": "post"},
            "team": None,
            "organization": None,
            "source_id": "comment-asset-id",
            "source_asset_type": "comment",
            "text": "hello world",
        },
    }

    event = parse_webhook_event(body)

    assert event.event_type == "comment"
    assert event.delivery_id == "11111111-1111-1111-1111-111111111111"
    assert event.recipient_user_id == "recipient-user-id"
    assert event.notification_ids == ("notif-id-1",)
    assert event.actor == WebhookActor(
        id="actor-user-id", username="alice", is_agent=False
    )
    assert event.actor_user_id == "actor-user-id"
    assert event.sender_username == "alice"
    assert event.asset == WebhookAssetRef(id="comment-asset-id", type="comment")
    assert event.root_asset == WebhookAssetRef(id="post-asset-id", type="post")
    assert event.source_id == "comment-asset-id"
    assert event.source_asset_type == "comment"


def test_parse_webhook_event_normalizes_underscored_event_name() -> None:
    body = {
        "event": "new_message",
        "data": {"conversation_id": "conv-1"},
    }
    event = parse_webhook_event(body)
    assert event.event_type == "new-message"
    assert event.conversation_id == "conv-1"


def test_parse_webhook_event_falls_back_to_id_for_new_conversation() -> None:
    body = {
        "event": "new-conversation",
        "data": {"id": "conv-2", "metadata": {"members": ["u1", "u2"]}},
    }
    event = parse_webhook_event(body)
    assert event.conversation_id == "conv-2"


def test_parse_webhook_event_merges_notification_ids_from_data() -> None:
    body = {
        "event": "comment",
        "notification_ids": ["a", "b"],
        "data": {"notification_id": "c", "notification_ids": ["a", "d"]},
    }
    event = parse_webhook_event(body)
    assert event.notification_ids == ("a", "b", "c", "d")


def test_parse_webhook_event_parses_asset_deleted() -> None:
    body = {
        "delivery_id": "22222222-2222-2222-2222-222222222222",
        "event": "asset.deleted",
        "timestamp": "2026-05-01T12:00:00Z",
        "user_id": "owner-user-id",
        "data": {
            "actor": {
                "id": "actor-user-id",
                "username": "alice",
                "is_agent": False,
            },
            "asset": {"id": "deleted-asset-id", "type": "post"},
            "team": {"id": "team-1", "name": "Research"},
            "organization": {"id": "org-1", "name": "Acme"},
        },
    }

    event = parse_webhook_event(body)

    assert event.event_type == "asset.deleted"
    assert event.asset == WebhookAssetRef(id="deleted-asset-id", type="post")
    assert event.actor_user_id == "actor-user-id"
    assert event.recipient_user_id == "owner-user-id"
    assert event.notification_ids == ()


def test_parse_webhook_event_handles_missing_actor_gracefully() -> None:
    body = {"event": "follow", "data": {}}
    event = parse_webhook_event(body)
    assert event.actor is None
    assert event.actor_user_id is None
    assert event.sender_username is None
