"""Tests for the webhook event parser and registry parity with ouro-js."""

from __future__ import annotations

import json
from pathlib import Path

from ouro.events import (
    WEBHOOK_EVENT_TYPES,
    WebhookActor,
    WebhookAssetRef,
    parse_webhook_event,
)


FIXTURES_DIR = Path(__file__).parent / "fixtures"


def test_event_registry_matches_ouro_js_snapshot() -> None:
    """Mirror parity with ouro-js src/schema/events.ts.

    The fixture is regenerated by `npx tsx ouro-js/scripts/dump-events.ts`
    when the registry changes.
    """
    snapshot = json.loads((FIXTURES_DIR / "webhook_events.json").read_text())
    assert tuple(snapshot) == WEBHOOK_EVENT_TYPES


def test_parse_webhook_event_parses_canonical_payload() -> None:
    body = {
        "delivery_id": "11111111-1111-1111-1111-111111111111",
        "event": "comment",
        "timestamp": "2026-01-01T00:00:00Z",
        "user_id": "recipient-user-id",
        "notification_id": "notif-id-1",
        "data": {
            "actor": {
                "id": "actor-user-id",
                "username": "alice",
                "is_agent": False,
            },
            "asset": {"id": "comment-asset-id", "type": "comment"},
            "parent_asset": {"id": "post-asset-id", "type": "post"},
            "root_asset": {"id": "post-asset-id", "type": "post"},
            "team": None,
            "organization": None,
            "source_id": "comment-asset-id",
            "source_asset_type": "comment",
            "text": "hello world",
        },
    }

    event = parse_webhook_event(body)

    assert event.event_type == "comment"
    assert event.delivery_id == "11111111-1111-1111-1111-111111111111"
    assert event.recipient_user_id == "recipient-user-id"
    assert event.notification_ids == ("notif-id-1",)
    assert event.actor == WebhookActor(
        id="actor-user-id", username="alice", is_agent=False
    )
    assert event.actor_user_id == "actor-user-id"
    assert event.sender_username == "alice"
    assert event.asset == WebhookAssetRef(id="comment-asset-id", type="comment")
    assert event.root_asset == WebhookAssetRef(id="post-asset-id", type="post")
    assert event.source_id == "comment-asset-id"
    assert event.source_asset_type == "comment"


def test_parse_webhook_event_normalizes_underscored_event_name() -> None:
    body = {
        "event": "new_message",
        "data": {"conversation_id": "conv-1"},
    }
    event = parse_webhook_event(body)
    assert event.event_type == "new-message"
    assert event.conversation_id == "conv-1"


def test_parse_webhook_event_falls_back_to_id_for_new_conversation() -> None:
    body = {
        "event": "new-conversation",
        "data": {"id": "conv-2", "metadata": {"members": ["u1", "u2"]}},
    }
    event = parse_webhook_event(body)
    assert event.conversation_id == "conv-2"


def test_parse_webhook_event_merges_notification_ids_from_data() -> None:
    body = {
        "event": "comment",
        "notification_ids": ["a", "b"],
        "data": {"notification_id": "c", "notification_ids": ["a", "d"]},
    }
    event = parse_webhook_event(body)
    assert event.notification_ids == ("a", "b", "c", "d")


def test_parse_webhook_event_parses_asset_deleted() -> None:
    body = {
        "delivery_id": "22222222-2222-2222-2222-222222222222",
        "event": "asset.deleted",
        "timestamp": "2026-05-01T12:00:00Z",
        "user_id": "owner-user-id",
        "data": {
            "actor": {
                "id": "actor-user-id",
                "username": "alice",
                "is_agent": False,
            },
            "asset": {"id": "deleted-asset-id", "type": "post"},
            "team": {"id": "team-1", "name": "Research"},
            "organization": {"id": "org-1", "name": "Acme"},
        },
    }

    event = parse_webhook_event(body)

    assert event.event_type == "asset.deleted"
    assert event.asset == WebhookAssetRef(id="deleted-asset-id", type="post")
    assert event.actor_user_id == "actor-user-id"
    assert event.recipient_user_id == "owner-user-id"
    assert event.notification_ids == ()


def test_parse_webhook_event_handles_missing_actor_gracefully() -> None:
    body = {"event": "follow", "data": {}}
    event = parse_webhook_event(body)
    assert event.actor is None
    assert event.actor_user_id is None
    assert event.sender_username is None


# ---------------------------------------------------------------------------
# verify_webhook_signature
# ---------------------------------------------------------------------------

import hashlib
import hmac

from ouro.events import verify_webhook_signature

_SECRET = "whsec_" + "ab" * 24
_BODY = b'{"event":"comment","delivery_id":"d-1","data":{}}'
_NOW = 1_790_000_000


def _sign(body: bytes, t: int, secret: str = _SECRET) -> str:
    digest = hmac.new(
        secret.encode(), f"{t}.".encode() + body, hashlib.sha256
    ).hexdigest()
    return f"t={t},v1={digest}"


def test_verify_webhook_signature_accepts_valid_signature() -> None:
    header = _sign(_BODY, _NOW)
    assert verify_webhook_signature(_BODY, header, _SECRET, now=_NOW)
    assert verify_webhook_signature(_BODY.decode(), header, _SECRET, now=_NOW)


def test_verify_webhook_signature_matches_backend_vector() -> None:
    # Node: createHmac("sha256", secret).update(`${t}.${body}`).digest("hex")
    header = (
        "t=1790000000,"
        "v1=" + hmac.new(
            _SECRET.encode(), b"1790000000." + _BODY, hashlib.sha256
        ).hexdigest()
    )
    assert verify_webhook_signature(_BODY, header, _SECRET, now=_NOW + 10)


def test_verify_webhook_signature_rejects_tampered_body_or_wrong_secret() -> None:
    header = _sign(_BODY, _NOW)
    assert not verify_webhook_signature(_BODY + b" ", header, _SECRET, now=_NOW)
    assert not verify_webhook_signature(_BODY, header, "whsec_other", now=_NOW)


def test_verify_webhook_signature_enforces_tolerance() -> None:
    header = _sign(_BODY, _NOW)
    assert verify_webhook_signature(_BODY, header, _SECRET, now=_NOW + 300)
    assert not verify_webhook_signature(_BODY, header, _SECRET, now=_NOW + 301)
    assert not verify_webhook_signature(_BODY, header, _SECRET, now=_NOW - 301)
    assert verify_webhook_signature(
        _BODY, header, _SECRET, tolerance=0, now=_NOW + 10_000
    )


def test_verify_webhook_signature_accepts_any_v1_for_rotation() -> None:
    good = _sign(_BODY, _NOW).split(",")[1]
    header = f"t={_NOW},v1={'0' * 64},{good}"
    assert verify_webhook_signature(_BODY, header, _SECRET, now=_NOW)


def test_verify_webhook_signature_rejects_malformed_headers() -> None:
    for header in (None, "", "garbage", f"t={_NOW}", "v1=abc", "t=soon,v1=abc"):
        assert not verify_webhook_signature(_BODY, header, _SECRET, now=_NOW)
    assert not verify_webhook_signature(_BODY, _sign(_BODY, _NOW), "", now=_NOW)
